export interface RoadmapPhase {
  phase: string;
  title: string;
  timeline: string;
  status: "done" | "next" | "future";
  goal: string;
  features: string[];
  revenueTarget: string;
  tech: string;
  note: string;
}

export const ROADMAP: RoadmapPhase[] = [
  {
    phase: "Phase 0",
    title: "MVP (College Project)",
    timeline: "Completed",
    status: "done",
    goal:
      "Build a working proof-of-concept that demonstrates the full IdleLink experience using simulated compute. Impress evaluators, validate the idea, and lay the technical foundation for everything that follows.",
    features: [
      "Email OTP verification (real SMTP)",
      "Sign in with Google (OAuth 2.0)",
      "Flutter mobile app (buy + sell)",
      "Next.js web app + admin panel",
      "AI Job Matcher",
      "Auto device spec detection",
      "Simulated live job progress bars",
      "In-app wallet with simulated payouts",
      "Real-time notifications (Socket.io)",
      "Ratings and reputation system",
    ],
    revenueTarget: "NPR 0 (college demo)",
    tech: "Flutter, Next.js, NestJS, MongoDB, Socket.io, Claude API, JWT, Nodemailer",
    note: "No real compute runs. Everything is simulated. The AI Matcher is the star feature.",
  },
  {
    phase: "Phase 1",
    title: "Real Payments & Verified Listings",
    timeline: "3–6 months",
    status: "next",
    goal:
      "Turn IdleLink from a demo into a real business. Integrate local payment gateways, verify sellers through KYC, and launch a closed beta with real users in Kathmandu. The goal is the first NPR transaction on the platform.",
    features: [
      "eSewa & Khalti integration (Nepal)",
      "Razorpay / Stripe (India market)",
      "Seller KYC verification (ID upload)",
      "Manual device listing verification",
      "Push notifications via Firebase FCM",
      "Transactional emails (SendGrid)",
      "Seller earnings analytics dashboard",
      "Weighted reputation score algorithm",
      "Referral system (invite to earn)",
      "Two-factor authentication (2FA)",
      "Automated weekly earnings reports",
      "Abuse reporting + admin review queue",
    ],
    revenueTarget: "NPR 5,000–20,000 / month",
    tech: "eSewa SDK, Khalti API, Stripe, Firebase FCM, SendGrid, AWS S3 (KYC docs), Twilio (SMS OTP)",
    note: "Closed beta in Kathmandu first. Target: 50 sellers, 100 buyers, NPR 50k in GMV within 3 months of launch.",
  },
  {
    phase: "Phase 2",
    title: "Real Compute Agent (“Easy Agent”)",
    timeline: "6–14 months",
    status: "future",
    goal:
      "Ship the IdleLink Agent — a lightweight background app that sellers install on their computer. For the first time, buyers' jobs will actually run on sellers' machines. This transforms IdleLink from a marketplace into a real compute infrastructure provider.",
    features: [
      "IdleLink Agent — desktop installer (Win/Mac/Linux)",
      "Real CPU/GPU utilization telemetry",
      "Docker-sandboxed job execution",
      "Live resource monitoring (seller dashboard)",
      "Availability scheduler (set hours of sharing)",
      "Real job logs streamed to buyer console",
      "Job isolation + memory limits + kill switch",
      "Idle detection — only runs when device is idle",
      "Job queue + retry system (Redis + BullMQ)",
      "In-app chat between buyer and seller",
      "Automatic payout on verified job completion",
      "Dispute resolution system",
    ],
    revenueTarget: "NPR 50,000–200,000 / month",
    tech: "Electron, Docker SDK, Prometheus, Grafana, Redis, BullMQ, WebSocket telemetry, Python sandbox runtime",
    note: "Hardest phase technically. Security and isolation are critical — a compromised device kills trust permanently.",
  },
  {
    phase: "Phase 3",
    title: "AI-Powered Matching v2 & Mobile Agent",
    timeline: "14–20 months",
    status: "future",
    goal:
      "Upgrade the NL Job Matcher from a simple AI lookup to a full recommendation engine that learns from past bookings. Add mobile device as a compute node — users can earn from their phone too. Expand to Android and iOS agent apps.",
    features: [
      "ML-based job-to-device matching (trained on real data)",
      "Matching learns from past booking success rates",
      "Android agent — share phone CPU/RAM while charging",
      "iOS agent (background processing mode)",
      "Predictive pricing — dynamic rates based on demand",
      "Advanced marketplace filters (TFLOPS, latency, region)",
      "Scheduled bookings (reserve a slot in advance)",
      "Recurring bookings for ongoing compute needs",
      "Favourites and saved device collections",
      "Referral leaderboard + social sharing",
      "Region-based compute routing (nearest device first)",
      "Compare devices side by side before booking",
    ],
    revenueTarget: "NPR 500,000–1,500,000 / month",
    tech: "PyTorch (matching model), FastAPI (ML service), React Native or Flutter for agent, Elasticsearch (search), PostHog (analytics)",
    note: "This phase is about making IdleLink feel intelligent, not just functional.",
  },
  {
    phase: "Phase 4",
    title: "Teams, SLA & GPU Clusters",
    timeline: "18–30 months",
    status: "future",
    goal:
      "Attract companies and research teams who need reliable, large-scale compute. Pool multiple seller devices into a virtual GPU cluster. Offer SLA guarantees so enterprise buyers trust the platform for production workloads.",
    features: [
      "Team accounts with org-level billing",
      "SLA tiers — 99.5% and 99.9% uptime guarantees",
      "GPU cluster pooling (merge multiple devices into one job)",
      "Public REST + GraphQL API for developers",
      "Python SDK — pip install idlelink",
      "JavaScript/TypeScript SDK — npm install idlelink",
      "Expand to India, Bangladesh, Southeast Asia",
      "Subscription plans for high-volume buyers",
      "Verified Premium Node badge for top sellers",
      "Dedicated enterprise support channel",
      "CI/CD integrations (GitHub Actions, GitLab)",
      "Automated invoicing and tax reporting",
    ],
    revenueTarget: "$5,000–$30,000 USD / month",
    tech: "Kubernetes, gRPC, Terraform, Multi-region MongoDB Atlas, Grafana + PagerDuty, Stripe Billing (subscriptions)",
    note: "First USD-denominated revenue milestone. This is where outside investors start paying attention.",
  },
  {
    phase: "Phase 5",
    title: "Developer Ecosystem & Marketplace",
    timeline: "24–36 months",
    status: "future",
    goal:
      "Open IdleLink to third-party developers. Let them build tools, plugins, and integrations on top of the platform. Create a marketplace where developers can sell ready-made compute templates and AI pipelines to buyers.",
    features: [
      "IdleLink Plugin Store — community-built add-ons",
      "Compute Templates — one-click job setup (LLM inference, video render, scraping)",
      "Webhook system for automation and integrations",
      "Zapier + Make (Integromat) native connectors",
      "Developer portal with full API docs + sandbox",
      "IdleLink Learn — tutorials for sellers and buyers",
      "Hackathons and compute grants for students",
      "Community forum + Discord integration",
      "Open source SDK and agent core",
      "Seller certification program (Verified Expert)",
      "Revenue sharing for plugin developers",
      "Translated platform — Nepali, Hindi, Bahasa Indonesia",
    ],
    revenueTarget: "$30,000–$100,000 USD / month",
    tech: "Developer portal (Docusaurus), Stripe Connect (plugin revenue share), OAuth 2.0 (third-party apps), GraphQL federation, CDN (Cloudflare)",
    note: "This phase creates a moat. When third-party developers build on IdleLink, switching costs become enormous.",
  },
  {
    phase: "Phase 6",
    title: "DePIN & Token Economy",
    timeline: "3–5 years",
    status: "future",
    goal:
      "Decentralize what's already working. Launch the $IDLE token to reward compute providers, use smart contracts for trustless escrow, and hand governance to the community via a DAO. This is when IdleLink becomes a true DePIN protocol and not just a company-owned platform.",
    features: [
      "$IDLE token — earned by sharing compute power",
      "Solidity smart contracts for escrow and payouts",
      "Deploy on Polygon / Base L2 (low transaction fees)",
      "DAO governance — token holders vote on platform decisions",
      "NFT node ownership certificates for premium sellers",
      "Trustless job verification using ZK proofs",
      "Staking mechanism — stake $IDLE to become a premium node",
      "Global node network targeting 50,000+ devices",
      "Token burn mechanism on every transaction (deflationary)",
      "DEX listing for $IDLE token",
      "Node operator rewards for highest uptime",
      "On-chain reputation scores for sellers",
    ],
    revenueTarget: "$500,000+ USD / month",
    tech: "Solidity, Hardhat, Polygon / Base, IPFS, Chainlink oracles, The Graph, wagmi, viem, OpenZeppelin",
    note: "Only decentralize what already works at scale. Blockchain should reduce friction — not be the product.",
  },
];
